# Generated by Django 4.2.7 on 2023-11-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('balance', models.IntegerField(default=0)),
                ('panCard', models.CharField(max_length=10)),
                ('aadharCard', models.CharField(max_length=12)),
            ],
        ),
    ]
