# Generated by Django 4.2.7 on 2023-11-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_cex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('receivers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers_id', to='auth_cex.user')),
                ('senders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders_id', to='auth_cex.user')),
            ],
        ),
    ]
