# Generated by Django 4.2.7 on 2023-11-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_cex', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionToSpendViaChild',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_id', to='auth_cex.user')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_id', to='auth_cex.user')),
            ],
        ),
    ]
